language: shell

services:
- docker


script:
- docker-compose run prospect

deploy:
  provider: releases
  github-token: $GITHUB_TOKEN
#  local_dir: dist
  file: {Prospect Mail-*.AppImage,prospect-mail_*.snap,prospect-mail-*.tar.gz}
#  file: "dist"
  skip_cleanup: true
  on:
    branch: main
    tags: true