if: (tag =~ /^v/)
language: shell
services:
- docker

script:
- docker-compose run prospect

deploy:
  provider: releases
  token: $GITHUB_TOKEN
#  local_dir: dist
  file_glob: true
  file:
    - $TRAVIS_BUILD_DIR/dist/Prospect Mail-*.AppImage
    - $TRAVIS_BUILD_DIR/dist/prospect-mail_*.snap
    - $TRAVIS_BUILD_DIR/dist/prospect-mail-*.tar.gz
#  file: "dist"
  skip_cleanup: true
  on:
    branch: main
    tags: true